config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/admin' => "rails_admin#maindashboard", as: 'dashboard'

  devise_for :users, controllers: {registrations: 'registrations'}
  
  # resources :posts
  # resources :topics
  # nesting posts to topics {restful conventions}
  resources :topics do
    resources :posts, except: [:index]
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	belongs_to :topic

	default_scope { order('created_at DESC') }
	# default_scope { order('title DESC') }

	validates :title, length: { minimum: 5 }, presence: true
	validates :body, length: { minimum: 5 }, presence: true
	validates :topic, presence: true
	validates :user, presence: true

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts

	self.per_page = 10
	# set per_page globally
	WillPaginate.per_page = 10

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, taken out {:recoverable, }
  devise :database_authenticatable, :registerable, :rememberable, :trackable #:validatable

  has_many :posts

  def admin?
  	role == 'admin'
  end

  def moderator?
  	role == 'moderator'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError do |exception|
  	redirect_to root_url, alert: exception.message
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # removed index action: nested posts to topics so no longer need

  def show
  	@post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  	@post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
  	@post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
  	if @post.save
  		flash[:notice] = "Post was saved."
  		redirect_to [@topic, @post]
  	else
  		flash[:error] = "There was an error saving the post. Please try again."
  		render :new
  	end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:id])
    authorize @post
  	if @post.update_attributes(post_params)
  		flash[:notice] = "The Post was updated"
  		redirect_to [@topic, @post]
  	else
  		flash[:notice] = "There was an error saving the post. Please try again."
  		render :edit
  	end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		@devise = build_resource({})
		authorize @devise
    	yield resource if block_given?
    	respond_with self.resource
    	
	end

	def create
		@devise = build_resource(sign_up_params)
		authorize @devise

    	resource.save
    	yield resource if block_given?
    	if resource.persisted?
      		if resource.active_for_authentication?
        		set_flash_message :notice, :signed_up if is_flashing_format?
        		sign_up(resource_name, resource)
        		respond_with resource, location: after_sign_up_path_for(resource)
      		else
        		set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        		expire_data_after_sign_in!
        		respond_with resource, location: after_inactive_sign_up_path_for(resource)
      		end
    	else
      		clean_up_passwords resource
      		set_minimum_password_length
      		respond_with resource
    	end
	end

	# DELETE /resource
  	def destroy
    	@devise = resource.destroy
    	authorize @devise
    	Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    	set_flash_message :notice, :destroyed if is_flashing_format?
    	yield resource if block_given?
    	respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  	#@topics = Topic.all
    @topics = Topic.limit(10).paginate(page: params[:page]) #, per_page: 10) see model
  	authorize @topics
  end

  def new
  	@topic = Topic.new
  	authorize @topic
  end

  def create
  	@topic = Topic.new(topic_params)
  	authorize @topic
  	if @topic.save
  		redirect_to @topic, notice: "Topic was saved successfully."
  	else
  		flash[:error] = "Error creating topic. Please try again."
       	render :new
  	end
  end

  def show
  	@topic = Topic.find(params[:id])
    #@posts = @topic.posts
    @posts = @topic.posts.limit(10).paginate(page: params[:page]) #, per_page: 10) see model
  	authorize @topic
  end

  def edit
  	@topic = Topic.find(params[:id])
  	authorize @topic
  end

  def update
  	@topic = Topic.find(params[:id])
  	authorize @topic
  	if @topic.update_attributes(topic_params)
  		redirect_to @topic
  	else
  		flash[:error] = "Error saving topic. Please try again."
  		render :edit
  	end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def my_name
		"Marcus Collier"
	end

	def form_group_tag(errors, &block)
		if errors.any?
			content_tag :div, capture(&block), class: 'form-group has-error'
		else
			content_tag :div, capture(&block), class: 'form-group'
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intranet</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
      <li><%= current_user.present? && current_user.role == 'admin' ? (link_to 'Admin', dashboard_path) : nil %></li>
			<li><%= link_to "SS Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
        Hello <%= link_to current_user.login, edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
		</ul>

		<% if flash[:notice] %>
        	<div class="alert alert-success">
           		<button type="button" class="close" data-dismiss="alert">&times;</button>
           		<%= flash[:notice] %>
         	</div>
       	<% elsif flash[:error] %>
         	<div class="alert alert-danger">
           		<button type="button" class="close" data-dismiss="alert">&times;</button>
           		<%= flash[:error] %>
         	</div>
       	<% elsif flash[:alert] %>
     		<div class="alert alert-warning">
           		<button type="button" class="close" data-dismiss="alert">&times;</button>
           		<%= flash[:alert] %>
         	</div>
       	<% end %>

	<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="col-md-8">
	<!-- changed form_for [@topic, @post] to local variables for partial -->
	<%= form_for [topic, post] do |f| %>
		<% if post.errors.any? %>
			<div class="alert alert-danger">
				<h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
				<ul>
					<% post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<%= form_group_tag(post.errors[:title]) do %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: 'Enter post title' %>
		<% end %>
		<%= form_group_tag(post.errors[:body]) do %>
			<%= f.label :body %>
			<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter post body' %>
		<% end %>

		<div>
			<%= f.label :title %>
			<%= f.select :title, options_for_select(["Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other", "Select One", "Cell", "Work", "Office", "Home", "Other"]) %>

			<select name="mycountry">
    <option value="Afghanistan">Afghanistan</option>
    <option value="Afrique du Sud">Afrique du Sud</option>
    <option value="Albanie">Albanie</option>
    <option value="Algérie">Algérie</option>
    <option value="Allemagne">Allemagne</option>
    <option value="Andorre">Andorre</option>
    <option value="Angola">Angola</option>
    <option value="Antigua et Barbuda">Antigua et Barbuda</option>
    <option value="Arabie saoudite">Arabie saoudite</option>
    <option value="Argentine">Argentine</option>
    <option value="Arménie">Arménie</option>
    <option value="Australie">Australie</option>
    <option value="Autriche">Autriche</option>
    <option value="Azerbaïdjan">Azerbaïdjan</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
    <option value="Hors Canada">Hors Canada</option>
</select>
		</div>
		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/posts/deleted_form_old.html.erb
 <%= form_for [topic, post] do |f| %>
   <div class="form-group">
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   </div>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/deleted_index.html.erb
<h1>All Posts</h1>
<% if policy(Post.new).create? %>
	<%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
<% end %>
<% @posts.find_each do |post| %>
	<div class="media">
		<div class="media-body">
			<h4 class="media-heading">
				<%= link_to post.title, post %>
			</h4>
			<small>
				submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.login %><br>
				
			</small>
		</div>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for posts</p>
		<ul>
			<li>Only submit posts that are revelant</li>
			<li>Limit to 5 a day</li>
		</ul>
	</div>

	<%= render partial: 'form', locals: {topic: @topic, post: @post} %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for posts</p>
		<ul>
			<li>Only submit posts that are revelant</li>
			<li>Limit to 5 a day</li>
		</ul>
	</div>
	
	<%= render partial: 'form', locals: {topic: @topic, post: @post} %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
 <h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       	<li>Only submit topics that are revelant</li>
		<li>Limit to 5 a day</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @topics %>
    </div>
  </div>
  <div class="col-md-4">
    <% if policy(Topic.new).create? %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
 <h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       	<li>Only submit topics that are revelant</li>
		<li>Limit to 5 a day</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
	<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>
     <% @posts.find_each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, [@topic, post] %>
           </h4>
           <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.login %><br>
           </small>
         </div>
       </div>
     <% end %>
     <div class="flickr_pagination">
      <%= will_paginate @posts %>
     </div>
   </div>
   <div class="col-md-4">
     <% if policy(Post.new).create? %>
       <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>About Security Scorecard</h1>
<p>Created by: <%= my_name %></p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Security Scorecard Intranet</h1>
  <p>This is the home page for Security Scorecard's Intranet</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %>
  </p>
</div>